name: flutter
version: 0.0.35-dev
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A framework for writing Flutter applications
homepage: http://flutter.io

dependencies:
  collection: '>=1.9.1 <2.0.0'
  http: '>=0.11.3+12'
  intl: '>=0.14.0 <0.16.0'
  meta: ^1.0.5
  typed_data: ^1.1.3
  vector_math: '>=2.0.3 <3.0.0'

  sky_engine:
    path: ../../bin/cache/pkg/sky_engine

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: "^2.0.2"

environment:
  sdk: '>=1.19.0 <2.0.0'
