name: dev_tools
description: Various repository development tools for flutter.

dependencies:
  archive: ^1.0.20
  args: ^0.13.4
  http: ^0.11.3+12
  intl: '>=0.14.0 <0.16.0'
  meta: ^1.0.5
  path: ^1.4.0
