name: flutter_test
version: 0.0.13-dev
dependencies:
  # The flutter tools depend on very specific internal implementation
  # details of the 'test' package, which change between versions, so
  # here we pin it precisely to avoid version skew across our
  # packages. When changing this, also update the pubspec.yaml files
  # for the flutter_tools and devicelab packages. All other packages
  # should depend on this one to transitively get the pinned version.
  test: 0.12.24+2

  # We use FakeAsync and other testing utilities.
  quiver: ^0.24.0

  flutter:
    sdk: flutter

  # We import stack_trace because the test packages uses it and we
  # need to be able to unmangle the stack traces that it passed to
  # stack_trace. See https://github.com/dart-lang/test/issues/590
  stack_trace: any # use version expected by test package

  # We override the createHttpClient in flutter with a MockClient.
  http: any # use version expected by flutter

  # Used by globalToLocal et al.
  vector_math: any # use version expected by flutter
